### PR TITLE
Add the maven upload script configuration

### PR DESCRIPTION
**Pull request by Airsaid**
- Add the maven upload script configuration

Execute `./gradlew publishAndroidSampleLibraryArtifactPublicationToMyMavenLocalRepository` task to publish all build artifacts to custom local repository directory.

### CODE REVIEW

**Comment by JackChen365** [comment]
Is it possible to extract all the sample-plugin related configurations to one single config file? So that we can easily maintain it and others could use it by applying `apply from: "xxx.gradle"`

**Comment by JackChen365** [comment]
Besides, should we make the upload plugin to a single Gradle file and we can use `local.properties` to enable it. So that will never be available for other developers who just wants to check the repo.

**Comment by Airsaid** [comment]
This is how it works now. All the configuration is in `maven-central-publish` and each module references it via `id("maven-central-publish")`.

**Review by JackChen365 — APPROVED** [review]
LGTM

**Pull request merged**
